version: '3.9'

services:
  database:
    image: mysql
    container_name: find_server
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: 'findserverisrunning'
      MYSQL_DATABASE: 'FIND_SERVER'
    ports: 
      - '3306:3306' 